### PR TITLE
Fix webpack test, fallback to npm.cmd when npm is not available

### PR DESCRIPTION
**Pull request by blutorange**
Alright I added a fallback for npm.cmd. Hope it should work now, but perhaps you can checkout this branch and test it first before merging.

### CODE REVIEW

**Comment by melloware** [comment]
I had to make one fix I just checked in.  I had to change `;` to `&` in the prepack step for it to work.

**Comment by blutorange** [comment]
@melloware  Ah right, I forgot about that. `&` is a bit problematic though, since it runs both commands in parallel, `&&` should works for windows & linux

**Comment by melloware** [comment]
I will fix!

**Comment by melloware** [comment]
Fixed to `&&`

**Comment by melloware** [comment]
I also just added an NPM build on Pull Requests that does `npm prepack`

**Pull request merged**
